### ISSUE TITLE
Why does gedcomx-rs specify extension elements?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-rs#6]
Why does gedcomx-rs specify [extension elements](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md#3-property-extensions)? All of the extension elements appear to be useful in the core model.

**Comment by stoicflame** [comment]
There are a variety of reasons, depending on which ones you're talking about.

For example, the "normalized" extensions were deemed to be specific to a given system. The presumption was that "System A" wasn't interested in knowing how "System B" normalized the "+2000-01-01" date.

Others were deemed to be "view-based conveniences" and not needed in the core. For example, display properties can each be calculated from the "core" data, but they're nice for web-based applications in an API.

The core model was focused on data exchange and fidelity, and tried not to make any presumptions about the producer/consumer nor the exchange media. Because of this, the spec was really careful to minimize the number of opportunities for data discrepancies. For example, by not adding the "normalized" extensions to the core spec, it didn't have to deal with questions like "what if the normalized and the formal dates are totally different? Which do I choose?." Likewise for display properties ("if the display gender is male, but the gender conclusion is female, which one is preferred?").

But the RS spec was focused on web-based API clients, so it could afford to designate things as "view-based" and "for display purposes only."
